-- Supabase Schema for Inventory Management System

-- 1. Create Suppliers Table
CREATE TABLE public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'Active',
    rating NUMERIC DEFAULT 0,
    total_orders INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Products Table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    location TEXT,
    quantity INTEGER DEFAULT 0,
    min_stock INTEGER DEFAULT 10,
    price NUMERIC NOT NULL,
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
    supplier_name TEXT, -- Keeping this temporarily for backward compatibility with your frontend
    barcode TEXT UNIQUE,
    expiry_date DATE,
    status TEXT DEFAULT 'In Stock',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Users Table (for app users, independent of Supabase Auth for now)
CREATE TABLE public.app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL,
    department TEXT,
    last_active TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Movement Records Table
CREATE TABLE public.movement_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    action TEXT NOT NULL, -- 'Added', 'Removed', 'Updated', 'Sold', 'Purchased', etc.
    quantity_change INTEGER NOT NULL,
    date DATE NOT NULL,
    user_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Purchase Orders Table
CREATE TABLE public.purchase_orders (
    id TEXT PRIMARY KEY, -- e.g. "PO-2024-0848"
    supplier_name TEXT NOT NULL,
    items INTEGER NOT NULL,
    total TEXT NOT NULL,
    date DATE NOT NULL,
    status TEXT DEFAULT 'Pending' -- 'Delivered', 'Pending', 'In Transit', 'Cancelled'
);

-- 6. Create Purchase Order Items Table
CREATE TABLE public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id TEXT REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    total NUMERIC NOT NULL
);

-- 7. Create Supplier Bills Table
CREATE TABLE public.supplier_bills (
    id TEXT PRIMARY KEY,
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
    supplier_name TEXT NOT NULL,
    date DATE NOT NULL,
    total_amount NUMERIC NOT NULL,
    created_by TEXT NOT NULL
);

-- 8. Create Supplier Bill Items Table
CREATE TABLE public.supplier_bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id TEXT REFERENCES public.supplier_bills(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    total NUMERIC NOT NULL
);

-- 9. Create Customer Bills Table
CREATE TABLE public.customer_bills (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    date DATE NOT NULL,
    total_amount NUMERIC NOT NULL,
    created_by TEXT NOT NULL
);

-- 10. Create Customer Bill Items Table
CREATE TABLE public.customer_bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id TEXT REFERENCES public.customer_bills(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    total NUMERIC NOT NULL
);

-- Add on-time delivery tracking columns to suppliers
ALTER TABLE public.suppliers
ADD COLUMN IF NOT EXISTS total_delivered INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS on_time_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS on_time_delivery NUMERIC DEFAULT 0;

-- Add image_url column to products
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS image_url TEXT;


